#!/bin/bash
test -e /sys/class/power_supply/BAT1/capacity || exit

CAP="$(cat /sys/class/power_supply/BAT1/capacity)"
BAT="$(cat /sys/class/power_supply/BAT1/status)$CAP"

case $BAT in
  Charging*)
    MESSAGE=" $CAP%"
    ;;
  Discharging[0-9]) # 0-9%
    MESSAGE=" $CAP%"
    ;;
  Discharging[1-2][0-9]) # 10-29%
    MESSAGE=" $CAP%"
    ;;
  Discharging[3-4][0-9]) # 30-49%
    MESSAGE=" $CAP%"
    ;;
  Discharging[5-6][0-9]) # 50-69%
    MESSAGE=" $CAP%"
    ;;
  Discharging[7-8][0-9]) # 70-89%
    MESSAGE=" $CAP%"
    ;;
  Discharging9[0-9]) # 90-99%
    MESSAGE=" $CAP%"
    ;;
  Discharging10[0-9]) # 100-109%
    MESSAGE=" $CAP%"
    ;;
esac
echo $MESSAGE
