#!/bin/bash

send_notification() {
    if [ ! -f "$HOME/.cache/batalert" ]; then
        notify-send "Battery Low!";
        touch ~/.cache/batalert;
    fi;
}

rm_batalert() {
    if test -f "$HOME/.cache/batalert"; then
        rm "$HOME/.cache/batalert";
    fi;
}

test -e /sys/class/power_supply/BAT1/capacity || exit

CAP="$(cat /sys/class/power_supply/BAT1/capacity)"
BAT="$(cat /sys/class/power_supply/BAT1/status)$CAP"

case $BAT in
    Charging*)
        export MESSAGE=" $CAP%"
        ;;
    Discharging[0-9]) # 0-9%
        export MESSAGE=" $CAP%"
        send_notification
        ;;
    Discharging[1-2][0-9]) # 10-29%
        export MESSAGE=" $CAP%"
        rm_batalert
        ;;
    Discharging[3-4][0-9]) # 30-49%
        export MESSAGE=" $CAP%"
        rm_batalert
        ;;
    Discharging[5-6][0-9]) # 50-69%
        export MESSAGE=" $CAP%"
        rm_batalert
        ;;
    Discharging[7-8][0-9]) # 70-89%
        export MESSAGE=" $CAP%"
        rm_batalert
        ;;
    Discharging9[0-9]) # 90-99%
        export MESSAGE=" $CAP%"
        rm_batalert
        ;;
    Discharging10[0-9]) # 100-109%
        export MESSAGE=" $CAP%"
        rm_batalert
        ;;
    Full*)
        export MESSAGE=" $CAP%"
        rm_batalert
        ;;
esac
echo "$MESSAGE"
